# npm-check-updates configuration used by yarn deps:check && yarn deps:update
# convenience scripts.
# @link https://github.com/raineorshine/npm-check-updates
reject: [
    # Need to adapt to the new version of the package.
    "redis",
    "@types/redis",
]
