defaultSemverRangePrefix: ""

nmMode: hardlinks-global

nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@^3.0.2":
    peerDependencies:
      typescript: ^4.3.5

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
