nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0-rc.8.cjs

# Packages sometimes forget to list their dependencies.
# In the past it used to cause many subtle issues, so Yarn now defaults to prevent such unsound accesses. Still, we don't want it to prevent you from doing your work as long as you can do it in a safe and predictable way,
# so we came up with the packageExtensions setting.
# @link https://yarnpkg.com/getting-started/migration#fix-dependencies-with-packageextensions
packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@^3.0.2":
    peerDependencies:
      "typescript": "^4.4.2"