coverage:
  status:
    patch: off
    project:
      default: off
      cacheInteropUnit:
        target: 1%
        flags:
          - cache_interop
      cacheIORedisUnit:
        target: 1%
        flags:
          - cache_ioredis
      cacheNodeRedisUnit:
        target: 0%
        flags:
          - cache_redis
      dsnParserUnit:
        target: 1%
        flags:
          - cache_dsn_parser
flags:
  dsnParserUnit:
    paths:
      - packages/dsn-parser/src
  cacheInteropUnit:
    paths:
      - packages/cache-interop/src
  cacheIORedisUnit:
    paths:
      - packages/cache-ioredis/src
  cacheNodeRedisUnit:
    paths:
      - packages/cache-redis/src
  e2e:
    paths:
      - packages/cache-ioredis/src
      - packages/cache-redis/src
      - packages/cache-interop/src

ignore:
  - "scripts/**/*"
  - "docs/**/*"
  - "scripts/**/*"
  - "**/index.ts"
  - "**/*.d.ts"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
