name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'soluble-io/tci'
    name: build, test, publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Check yarn.lock
        run: sh ./scripts/check-git-pristine-yarn-lock.sh

      - name: Typecheck
        run: |
          yarn typecheck

      - name: Tests
        run: |
          yarn test
        env:
          CI: true

      #- name: Potentially save npm token
      #  run: |
      #    ([[ ! -z ${{ secrets.NPM_TOKEN }} ]] && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc) || echo "Did not write npm token"

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@soluble:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Cat token
        run: |
          - cat .npmrc

      - name: Whoami
        run: |
          - npm whoami

      - name: Potentially publish canary to npm
        run: |
          if \
            ls ~/.npmrc >/dev/null 2>&1 && \
            [[ $(git describe --exact-match 2> /dev/null || :) =~ -canary ]]; \
          then
            yarn run lerna publish from-git --npm-tag canary --yes
          else
            echo "Did not publish canary"
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY_BYPASS: true
      - name: Potentially publish stable to npm
        run: |
          if \
            ls ~/.npmrc >/dev/null 2>&1 && \
            [[ ! $(git describe --exact-match 2> /dev/null || :) =~ -canary ]]; \
          then
            yarn run lerna publish from-git --yes
          else
            echo "Did not publish"
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY_BYPASS: true
